doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_token: 'App\Infrastructure\Persistence\Doctrine\Types\TokenType'
            user_email: 'App\Infrastructure\Persistence\Doctrine\Types\EmailType'
            blog_id: 'App\Infrastructure\Persistence\Doctrine\Types\BlogIdType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Model'
                prefix: 'App\Domain\Model'
                alias: App
