version: '3'
services:
    nginx-api:
        build:
            context: ./docker/development/nginx/api
        volumes:
            - ./:/var/www
        ports:
            - "81:80"
        depends_on:
            - php-fpm

    nginx-web:
        build:
            context: ./docker/development/nginx/web
        volumes:
            - ./frontend:/var/www
        ports:
            - "82:80"

    node-js:
        image: node:17-alpine
        user: node
        working_dir: /usr/src/
        volumes:
            - ./frontend:/usr/src
        ports:
            - "3000:3000"

    php-fpm:
        build:
            context: ./docker/development/php-fpm
        volumes:
            - ./:/var/www

    php-cli:
        build:
            context: ./docker/development/php-cli
        volumes:
            - ./:/var/www
            - composer:/root/.composer/cache

    postgres:
        image: postgres:14.1-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: blog
        ports:
            - "54329:5432"

    mailer:
        image: mailhog/mailhog
        ports:
            - "8086:8025"
            - "1025:1025"

    #redis:
    #    image: redis:5.0-alpine
    #    volumes:
    #        - redis:/data
    #    command:
    #        - 'redis-server'
    #        - '--databases 2'
    #        - '--save 900 1'
    #        - '--save 300 10'
    #        - '--save 60 10000'
    #        - '--requirepass secret'



volumes:
    composer:
    postgres:
#    redis: